modules/webform-8.x-5.2/webform/src/Form/WebformResultsClearForm.php
<?php

namespace Drupal\webform\Form;

use Drupal\Core\Form\FormStateInterface;

/**
 * Webform for webform results clear webform.
 */
class WebformResultsClearForm extends WebformSubmissionsDeleteFormBase {

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'webform_results_clear';
  }

  /**
   * {@inheritdoc}
   */
  public function getQuestion() {
    $t_args = ['%label' => $this->getLabel()];
    return $this->t('Clear all %label submissions?', $t_args);
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $submission_total = $this->submissionStorage->getTotal($this->webform, $this->sourceEntity);
    if ($submission_total) {
      return parent::buildForm($form, $form_state);
    }
    else {
      $t_args = ['%label' => $this->getLabel()];
      $form['message'] = [
        '#type' => 'webform_message',
        '#message_type' => 'error',
        '#message_message' => $this->t('There are no %label submissions.', $t_args),
      ];
      return $form;
    }
  }

  /**
   * {@inheritdoc}
   */
  public function getWarning() {
    $t_args = ['%label' => $this->getLabel()];
    return [
      '#type' => 'webform_message',
      '#message_type' => 'warning',
      '#message_message' => $this->t('Are you sure you want to clear all %label submissions?', $t_args) . '<br/>' .
        '<strong>' . $this->t('This action cannot be undone.') . '</strong>',
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    $submission_total = $this->submissionStorage->getTotal($this->webform, $this->sourceEntity);

    $t_args = [
      '%label' => $this->getLabel(),
      '@total' => $submission_total,
      '@submissions' => $this->formatPlural($submission_total, 'submission', 'submissions'),
    ];

    return [
      'title' => [
        '#markup' => $this->t('This action will…'),
      ],
      'list' => [
        '#theme' => 'item_list',
        '#items' => [
          $this->t('Remove @total %label @submissions', $t_args),
          ['#markup' => '<em>' . $this->t('Take a few minutes to complete') . '</em>'],
        ],
      ],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getConfirmInput() {
    $t_args = ['%label' => $this->getLabel()];
    return [
      '#type' => 'checkbox',
      '#title' => $this->t('Yes, I want to clear all %label submissions', $t_args),
      '#required' => TRUE,
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getCancelUrl() {
    return $this->requestHandler->getUrl($this->webform, $this->sourceEntity, 'webform.results_submissions');
  }

  /**
   * {@inheritdoc}
   */
  public function getMessage() {
    $t_args = ['%label' => $this->getLabel()];
    $this->t('Webform %label submissions cleared.', $t_args);
  }

}

modules/webform-8.x-5.2/webform/templates/webform-actions.html.twig
{#
/**
 * @file
 * Default theme implementation of a webform actions.
 *
 * @see template_preprocess_webform_actions()
 * @see \Drupal\webform\WebformSubmissionForm::actionsElement
 * @see \Drupal\webform\WebformSubmissionForm::actions
 *
 * @ingroup themeable
 */
#}
{{ element }}

modules/webform-8.x-5.2/webform/templates/webform-composite-link.html.twig
{#
/**
 * @file
 * Default theme implementation of a link composite webform element.
 *
 * Available variables:
 * - content: The link webform element to be output.

 * @see template_preprocess_webform_composite_link()
 *
 * @ingroup themeable
 */
#}
{{ content }}

modules/webform-8.x-5.2/webform/templates/webform-composite-name.html.twig
{#
/**
 * @file
 * Default theme implementation of a name composite webform element.
 *
 * Available variables:
 * - content: The name webform element to be output.
 * - flexbox: Determines if Flexbox layout should be applied to the composite
 *   element.
 *
 * @see template_preprocess_webform_composite_name()
 *
 * @ingroup themeable
 */
#}
{% if flexbox %}
  <div class="webform-flexbox">
    {% if content.title %}
      <div class="webform-flex webform-flex--2"><div class="webform-flex--container">{{ content.title }}</div></div>
    {% endif %}
    {% if content.first %}
      <div class="webform-flex webform-flex--3"><div class="webform-flex--container">{{ content.first }}</div></div>
    {% endif %}
    {% if content.middle %}
      <div class="webform-flex webform-flex--2"><div class="webform-flex--container">{{ content.middle }}</div></div>
    {% endif %}
    {% if content.last %}
      <div class="webform-flex webform-flex--3"><div class="webform-flex--container">{{ content.last }}</div></div>
    {% endif %}
    {% if content.suffix %}
      <div class="webform-flex webform-flex--1"><div class="webform-flex--container">{{ content.suffix }}</div></div>
    {% endif %}
    {% if content.degree %}
      <div class="webform-flex webform-flex--1"><div class="webform-flex--container">{{ content.degree }}</div></div>
    {% endif %}
  </div>
{% else %}
  {{ content }}
{% endif %}

modules/webform-8.x-5.2/webform/templates/webform-contribute.html.twig
{#
/**
 * @file
 * Default theme implementation for the webform contribute community info.
 *
 * Available variables:
 * - account: The user or organization account profile.
 * - membership: The user or organizations membership status.
 * - contribution: The user or organizations contributions.
 */
#}
{{ attach_library('webform/webform.contribute') }}

<div class="webform-contribute-community-info">
  <h2 class="webform-contribute-community-info__header">{{ 'Community Information'|t }}</h2>
  <div class="webform-contribute-community-info__items">
    <div class="webform-contribute-community-info__item">
      <span class="webform-contribute-community-info__item-icon webform-contribute-community-info__item-icon--account" id="contribute-info-account"></span>
      <div class="webform-contribute-community-info__item-details">
        <h3 class="webform-contribute-community-info__item-title">{{ 'Drupal.org Account'|t }}</h3>
        {{ account.value }}
        {% if account.description %}
          <br/>{{ account.description }}
        {% endif %}
      </div>
    </div>
    <div class="webform-contribute-community-info__item">
      <span class="webform-contribute-community-info__item-icon webform-contribute-community-info__item-icon--membership" id="contribute-info-membership"></span>
      <div class="webform-contribute-community-info__item-details">
        <h3 class="webform-contribute-community-info__item-title">{{ 'Drupal Association Membership'|t }}</h3>
        {{ membership.value }}
        {% if membership.description %}
          <br/>{{ membership.description }}
        {% endif %}
      </div>
    </div>
    <div class="webform-contribute-community-info__item">
      <span class="webform-contribute-community-info__item-icon webform-contribute-community-info__item-icon--contribution" id="contribute-info-contribution"></span>
      <div class="webform-contribute-community-info__item-details">
        <h3 class="webform-contribute-community-info__item-title">{{ 'Contributions to Drupal'|t }}</h3>
        {{ contribution.value }}
        {% if contribution.description %}
          <br/>{{ contribution.description }}
        {% endif %}
      </div>
    </div>
  </div>
</div>

modules/webform-8.x-5.2/webform/templates/webform-element-document-file.html.twig
{#
/**
 * @file
 * Default theme implementation for a document file element.
 *
 * Available variables:
 * - element: The element.
 * - value: The element's value.
 * - options Associative array of options for element.
 * - file: The element's File object.
 * - file_link: Link to the file.
 */
#}
<div>{{ file_link }}</div>

modules/webform-8.x-5.2/webform/templates/webform-element-image-file.html.twig
{#
/**
 * @file
 * Default theme implementation for an image file element.
 *
 * Available variables:
 * - element: The element.
 * - value: The element's value.
 * - options Associative array of options for element.
 * - file: The element's File object.
 * - uri: The element's URI.
 * - style_name: The image style name.
 * - format: The image display format.
 * - image: The image.
 */
#}
{{ attach_library('webform/webform.element.image_file') }}
{{ image }}

modules/webform-8.x-5.2/webform/templates/webform-element-video-file.html.twig
{#
/**
 * @file
 * Default theme implementation for a video file element.
 *
 * Available variables:
 * - element: The element.
 * - value: The element's value.
 * - options Associative array of options for element.
 * - file: The element's File object.
 * - file_link: Link to the file.
 *
 * @see http://caniuse.com/#feat=video
 * @see http://www.w3schools.com/html/html5_audio.asp
 */
#}
{% if extension == 'mp4' %}
  {{ attach_library('webform/webform.element.video_file') }}
  <div class="webform-video-file">
    <video width="620" height="349" controls>
      <source src="{{ uri }}" type="{{ type }}">
    </video>
  </div>
{% endif %}
<div>{{ file_link }}</div>

modules/webform-8.x-5.2/webform/templates/webform-email-message-html.html.twig
{#
/**
 * @file
 * Default theme implementation for webform email wrapper template as HTML.
 *
 * Available variables:
 * - message: The email message which contains to, from, subject, message, etc…
 * - webform_submission: The webform submission.
 * - handler: The webform handler.
 *
 * @ingroup themeable
 */
#}
{{ message.body }}

modules/webform-8.x-5.2/webform/templates/webform-email-message-text.html.twig
{#
/**
 * @file
 * Default theme implementation for webform email wrapper template as plain text.
 *
 * Available variables:
 * - message: The email message which contains to, from, subject, message, etc…
 * - webform_submission: The webform submission.
 * - handler: The webform handler.
 *
 * @ingroup themeable
 */
#}
{{ message.body }}

modules/webform-8.x-5.2/webform/templates/webform-help-video-youtube.html.twig
{#
/**
 * @file
 * Theme implementation for webform help video using YouTube.
 *
 * Available variables
 * - youtube_id: YouTube video id.
 *
 * @ingroup themeable
 */
#}
{{ attach_library('webform/webform.help') }}
<div class="webform-help-video-youtube">
  <div class="webform-help-video-youtube--container">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ youtube_id }}?rel=0&modestbranding=1{{ autoplay ? '&autoplay=1' : '' }}"{{ autoplay ? 'allow="autoplay"' : '' }} frameborder="0" allowfullscreen></iframe>
  </div>
</div>

modules/webform-8.x-5.2/webform/templates/webform-horizontal-rule.html.twig
{#
/**
 * @file
 * Default theme implementation of a Webform horizontal_rule element.
 *
 * Available variables:
 * - attributes: HTML attributes for the horizontal_rule element.
 *
 * @see template_preprocess_webform_horizontal_rule()
 *
 * @ingroup themeable
 */
#}
{{ attach_library('webform/webform.element.horizontal_rule') }}
{%
set classes = [
  'webform-horizontal-rule',
]
%}
<hr{{ attributes.addClass(classes) }} />

modules/webform-8.x-5.2/webform/templates/webform-progress-tracker.html.twig
{#
/**
 * @file
 * Default theme implementation for webform wizard progress tracker.
 *
 * Available variables:
 * - webform: A webform.
 * - pages: Associatve array of wizard pages.
 * - progress: Array of wizard progress containing page titles.
 * - current_page: Current wizard page key.
 * - current_index: The current wizard page index.
 * - max_pages: Maximum number of pages that progress text should be displayed on.
 *
 * @see template_preprocess_webform_progress_bar()
 * @see https://www.w3.org/WAI/tutorials/forms/multi-page/
 *
 * @ingroup themeable
 */
#}
{{ attach_library('webform/webform.progress.tracker') }}

<ul class="webform-progress-tracker progress-tracker progress-tracker--center">
  {% for index, page in progress %}
    {% set is_completed = index < current_index %}
    {% set is_active = index == current_index %}
    {%
      set classes = [
        'progress-step',
        is_completed ? 'is-complete',
        is_active ? 'is-active',
      ]
    %}
    <li{{ attributes.setAttribute('data-webform-page', page.name).setAttribute('title', page.title).setAttribute('class', '').addClass(classes) }}>
      <span class="progress-marker">{{ index + 1 }}</span>
      {% if progress|length < max_pages %}
        <span class="progress-text">
          <span class="progress-title">
            {% if is_active or is_completed %}
              <span class="visually-hidden">{{ is_active ? 'Current'|t : 'Completed'|t }}: </span>
            {% endif %}
            {{ page.title }}
          </span>
        </span>
      {% endif %}
    </li>
  {% endfor %}
</ul>

modules/webform-8.x-5.2/webform/templates/webform-progress.html.twig
{#
/**
 * @file
 * Default theme implementation for webform wizard progress.
 *
 * Available variables:
 * - webform: A webform.
 * - pages: Array of wizard pages.
 * - current_page: Current wizard page.
 * - total_pages: Current wizard page.
 * - summary: Summary of progress.
 * - percentage: Percentage completed.
 * - bar: A progress bar.
 *
 * @see template_preprocess_webform_progress()
 *
 * @ingroup themeable
 */
#}
{{ attach_library('webform/webform.progress') }}

<div class="webform-progress">

  {{ bar }}

  {% if summary or percentage %}
    <div class="webform-progress__status">
      {% if summary %}
        <span class="webform-progress__summary">{{ summary }}</span>
        {% if percentage %}
          <span class="webform-progress__percentage">({{ percentage }})</span>
        {% endif %}
      {% else %}
        <span class="webform-progress__percentage">{{ percentage }}</span>
      {% endif %}
    </div>
  {% endif %}

</div>

modules/webform-8.x-5.2/webform/templates/webform-submission-form.html.twig
{#
/**
 * @file
 * Default theme implementation for a webform submission form.
 *
 * Available variables:
 * - form: The webform submission form.
 *
 * @ingroup themeable
 */
#}
{{ form }}